config/routes.rb
Rails.application.routes.draw do

  root 'posts#index'

  devise_for :users

  resources :users, only: [:index, :show] do
    resources :friendships, only: [:create] 
    member do
      get 'confirm'
      get 'deny'
    end
  end
  resources :posts, only: [:index, :create] do
    resources :comments, only: [:create]
    resources :likes, only: [:create, :destroy]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: 'User'

  def confirm_friend
    update_attributes(status: true)
    Friendship.create!(friend_id: user_id,
                       user_id: friend_id,
                       status: true)
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true, length: { maximum: 20 }

  has_many :posts
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  has_many :confirmed_friendships, -> { where status: true }, class_name: 'Friendship'
  has_many :friends, through: :confirmed_friendships

  has_many :pending_friendships, -> { where status: false }, class_name: 'Friendship', foreign_key: 'user_id'
  has_many :pending_friends, through: :pending_friendships, source: :friend

  has_many :inverse_friendships, -> { where status: false }, class_name: 'Friendship', foreign_key: 'friend_id'
  has_many :friend_requests, through: :inverse_friendships, source: :user

  def friends_and_own_posts
    Post.where(user: (friends.to_a << self))
  end

  def friend?(user)
    friends.include?(user)
  end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  include ApplicationHelper

  def create
    @user = User.find(params[:user_id])
    return if already_sended?(@user)
    return if sended_to_us?(@user)

    return if current_user == @user

    @friendship = current_user.pending_friendships.build(friend_id: params[:user_id], status: false)
    if @friendship.save
      redirect_to root_path
      flash[:notice] = 'Friend request sended'
    else
      flash[:notice] = 'somthing happened'
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!

  def index
    @post = Post.new
    timeline_posts
  end

  def create
    @post = current_user.posts.new(post_params)

    if @post.save
      redirect_to posts_path, notice: 'Post was successfully created.'
    else
      timeline_posts
      render :index, alert: 'Post was not created.'
    end
  end

  private

  def timeline_posts
    @timeline_posts ||= current_user.friends_and_own_posts.ordered_by_most_recent.includes(:user)
  end

  def post_params
    params.require(:post).permit(:content)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
    @friends = current_user.friends.filter { |friend| friend if friend != current_user }
    @pending_requests = current_user.pending_friends
    @friend_requests = current_user.friend_requests
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.ordered_by_most_recent
  end

  def confirm
    @user = User.find(params[:id])
    @friendship = current_user.inverse_friendships.find { |friendship| friendship.user == @user }
    @friendship.update(status: true)
    Friendship.create!(friend_id: current_user.id,
                       user_id: @user.id,
                       status: true)

    redirect_to root_path
    flash[:notice] = 'Friend request accepted'
  end

  def deny
    @user = User.find(params[:id])
    @friendship = current_user.inverse_friendships.find { |friendship| friendship.user == @user }
    @friendship.destroy
    redirect_to root_path
    flash[:notice] = 'You have denied the friendship request'
  end

  def friend?(user)
    friends.include?(user)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def friend?(user); end

  def already_sended?(user)
    return unless current_user.pending_friendships.any? { |friendship| friendship.friend_id == user }

    redirect_to root_path
    flash[:notice] = 'you already sent a request to this person'
  end

  def sended_to_us?(_user)
    return unless current_user.inverse_friendships.any? { |friendship| friendship.user == current_user }

    redirect_to root_path
    flash[:notice] = 'this person already sent a request to you'
  end

  def menu_link_to(link_text, link_path)
    class_name = current_page?(link_path) ? 'menu-item active' : 'menu-item'

    content_tag(:div, class: class_name) do
      link_to link_text, link_path
    end
  end

  def like_or_dislike_btn(post)
    like = Like.find_by(post: post, user: current_user)
    if like
      link_to('Dislike!', post_like_path(id: like.id, post_id: post.id), method: :delete)
    else
      link_to('Like!', post_likes_path(post_id: post.id), method: :post)
    end
  end

  def btn_send(user)
    return if current_user.pending_friends.include?(user)
    return if current_user.friends.include?(user)
    return if current_user.friend_requests.include?(user)

    (button_to 'Send request', user_friendships_path(user), method: :post)
  end

  def btn_mutual(user)
    return if user.friends.include?(nil)

    mutuals = []
    user.friends.map do |friend|
      current_user.friends.map { |friendd| friendd == friend ? mutuals.push(friend.name) : mutuals }
    end
    mutuals.uniq
  end

  def all_users(user)
    return unless user != current_user

    content_tag(:div) do
      content_tag(:h4, user.name) +
        (link_to 'See Profile', user_path(user)) +
        btn_send(user) +
        btn_mutual(user)
    end
  end

  def user_sessionss
    if current_user
      content_tag(:div) do
        (button_to 'Sign out', destroy_user_session_path, method: :delete)
      end
    else
      (button_to 'Sign in', new_user_session_path) +
        (link_to 'Sign up', new_user_registration_path)
    end
  end

  def notice?
    return unless notice.present?

    content_tag(:div, class: 'notice') do
      notice
    end
  end

  def alert?
    return unless alert.present?

    content_tag(:div, class: 'notice') do
      alert
    end
  end
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/post_helper.rb
module PostHelper
  def display_errors(post)
    return unless post.errors.full_messages.any?

    content_tag :p, "Post could not be saved. #{post.errors.full_messages.join('. ')}", class: 'errors'
  end

  def post_of_friend?(post)
    post.user.friend?(current_user) || post.user == current_user
  end
end

app/views/layouts/_allert.html.erb
<%= notice? %>

<%= alert? %>

app/views/layouts/_header.html.erb
      <%=  user_sessionss %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RorSocialScaffold</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <nav class="nav">
      <%= link_to 'Stay in touch', root_path %>
      <div class="menu">
        <div class="menu-item">
          <%= menu_link_to 'Timeline', posts_path %>
        </div>
        
          <%= menu_link_to 'All users', users_path %>
          <%= render 'layouts/header' %>
        </div>
      </div>
      <div class='menu-item'>
      </div>
    </nav>
    <%= render 'layouts/allert' %>
    <main class="main">
      <%= yield %>
    </main>
  </body>
</html>

app/views/posts/_post.html.erb
  <li class="post">
    <div>
      <div class='post-attribution' >
        <%= link_to post.user.name, user_path(post.user), class: 'post-author' %>
      </div>
      <div class='post-liking'>
        <span class='post-date'> <%= post.created_at.strftime("%Y/%m/%d") %> </span>
        <%= like_or_dislike_btn(post) %>
        <%= post.likes.count%>  Likes!
      </div>
    </div>
    <p class="post-content">
      <%= post.content %>
    </p>

    <div class='post-comments-section'>
      <%= post.comments.count%>  Comments
      <%= render partial: 'comments/comment', collection: post.comments %>

      <%= form_for(post.comments.new, url: post_comments_path(post)) do |form| %>
        <%= form.text_field :content, id: :comment_content, class: 'form-control', placeholder: 'Add new Comment' %>
        <%= form.submit 'Comment', class: 'btn btn-secondary' %>
      <% end %>
    </div>
  </li>

app/views/posts/index.html.erb
<%= form_for(@post) do |form| %>
  <%= form.label :content %>
  <%= form.text_field :content, id: :post_content, class: 'form-control', placeholder: 'Add New Post' %>
  <%= display_errors(@post) %>
  <%= form.submit 'Save', class: 'btn btn-primary' %>
<% end %>

<article class="timeline">
  <h3>
    Recent posts
  </h3>
  <ul class="posts">
    <%= render @timeline_posts %>
  </ul>
</article>

app/views/users/_user.html.erb
<%= all_users(user) %>

app/views/users/index.html.erb
<section class="users-section">
  <ul class="users-list">
    <%= render @users %>
  </ul>
</section>


<br/><br/>



  <h2> friends</h2>
  <% @friends.uniq.each do |friend|%>
    <%= friend.name %><br/>
  <% end%>


<br/><br/>

<h2> recieved requests</h2>
<% @friend_requests.each do |friend|%>
  <%= friend.name %><br/>
  <%= link_to 'Confirm', confirm_user_path(friend) %>
  <%= link_to 'Deny', deny_user_path(friend) %>
<% end%>


<br/><br/>

<h2> pending requests</h2>
<% @pending_requests.each do |friend|%>
  <%= friend.name %><br/>
<% end%>

app/views/users/show.html.erb
<section class="user-section">
  <h2><%= "Name: #{@user.name}" %></h2>
      <%= btn_send(@user) %>
  <article class="timeline">
    <h3>Recent posts:</h3>
    <ul class="posts">
      <%= render @posts %>
    </ul>
  </article>
</section>